### ISSUE TITLE
Some user menu buttons aren't synced

### ISSUE THREAD

**Issue by polycone** [onimp/oni_multiplayer#118] opened 2023-06-23 22:16 UTC
![image](https://github.com/zuev93/oni_multiplayer/assets/10905879/a499f355-e120-408d-bea9-03614ba1c0d7)

I clicked on Cancel Dig on the server and that action hadn't happened on the client.
The same is for Cancel Mop.

**_Note: I haven't checked all the buttons._**

**Comment by zuev93** [comment] 2023-07-02 09:00
Checked:
This is caused due to KPrefabeId desyncs. This is happening for new objects that are created after a sync.

Sync in general works.

So after #126 is complete we need to switch from KPrefabeId to our own MultiplayerIds and the sync will work reliably.

**Comment by zuev93** [comment] 2023-07-13 21:00
So user menu patch switched to MultiplayerReference and works as other sync patches.

In meanwhile this bug still reproducable for non synced building ghost. 

We have a ticket to sync building MultiplayerIds which will eventyually fix this bug. Therefore closing this ticket in favor of #133

**Closed by zuev93** 2023-07-13 21:00 UTC
Labels: bug
